
columns:

  InvoiceNo : object
  StockCode  : object
  Description  : object
  Quantity : int64
  InvoiceDate : datetime64[ns]
  UnitPrice : float64
  CustomerID : float64
  Country : object

numerical_columns:
- Quantity
- UnitPrice
- CustomerID

categorical_columns:
- InvoiceNo
- StockCode
- Description
- InvoiceDate
- Country
